using System.Text.Json.Nodes;
using Anthill.Core.Common;
using Anthill.Core.Configuration;
using Anthill.Core.Domain;
using Anthill.Core.Native;

namespace Anthill.Core.Pheromones;

/// <summary>
/// Mission success scoring. The arithmetic is delegated to the native C++ kernel
/// (<see cref="NativeKernel.ScoreMission"/>) — one of the hot paths the hybrid split
/// targets — with a bit-identical managed fallback. Quality flags (builder bonus,
/// verifier verdict) are derived here in managed code where the text lives.
/// </summary>
public sealed class PheromoneEngine
{
    public const int QualityBonusThreshold = 1500;

    public double ScoreMission(Mission mission)
    {
        var total = mission.Tasks.Count;
        if (total == 0) return 0.0;
        var completed = mission.Tasks.Count(t => t.Status == TaskStatus.Complete);
        var failed = mission.Tasks.Count(t => t.Status == TaskStatus.Failed);
        var skipped = mission.Tasks.Count(t => t.Status == TaskStatus.Skipped);

        var builderResults = mission.Tasks
            .Where(t => (t.AssignedAnt is "builder" or "coder") && !string.IsNullOrEmpty(t.Result))
            .Select(t => t.Result!);
        var builderBonus = string.Join("\n", builderResults).Length > QualityBonusThreshold;

        var verifierResults = mission.Tasks
            .Where(t => t.AssignedAnt == "verifier" && !string.IsNullOrEmpty(t.Result))
            .Select(t => t.Result!);
        var verdict = TextUtil.ExtractVerdict(string.Join("\n", verifierResults));
        var verdictCode = verdict switch { "failed" => -1, "needs_improvement" => 0, "passed" => 1, _ => 2 };

        return NativeKernel.ScoreMission(total, completed, failed, skipped, builderBonus, verdictCode);
    }
}

/// <summary>
/// Parses a coder ant's JSON response into a validated <see cref="PatchSet"/>. Enforces
/// the safe-path contract, content truncation, and the requires-approval invariant, exactly
/// as the Python <c>PatchProposalParser</c> did. Throws on structurally invalid input.
/// </summary>
public sealed class PatchProposalParser
{
    public PatchSet Parse(string rawText, string missionId, string taskId)
    {
        var parsed = Json.ExtractJsonObject(rawText);
        var summary = (parsed["summary"]?.GetValue<string>() ?? "").Trim();
        if (summary.Length == 0) summary = "Structured patch proposal generated by CoderAnt.";

        if (parsed["proposals"] is not JsonArray rawProposals)
            throw new ArgumentException("'proposals' must be a list.");

        var proposals = new List<PatchProposal>();
        foreach (var item in rawProposals.Take(AnthillRuntime.MaxPatchProposalsPerSet))
        {
            if (item is not JsonObject obj) continue;
            // Parse each proposal independently: one malformed entry (a placeholder path, a missing
            // reason) shouldn't discard the valid proposals alongside it in the same set.
            try
            {
                var filePath = Validation.ValidateSafePatchPath((obj["file_path"]?.GetValue<string>() ?? "").Trim());
                var changeType = (obj["change_type"]?.GetValue<string>() ?? "modify").Trim().ToLowerInvariant();
                var reason = (obj["reason"]?.GetValue<string>() ?? "").Trim();
                var risk = (obj["risk"]?.GetValue<string>() ?? "").Trim();
                // GetValue<string>() throws on JSON null nodes — must check ValueKind first
                var oldContent = JsonStrOrNull(obj["old_content"]);
                var newContent = JsonStrOrNull(obj["new_content"]);
                if (oldContent is not null) oldContent = TextUtil.Truncate(oldContent, AnthillRuntime.MaxPatchContentChars, "...[old_content truncated]");
                if (newContent is not null) newContent = TextUtil.Truncate(newContent, AnthillRuntime.MaxPatchContentChars, "...[new_content truncated]");
                if (reason.Length == 0) reason = "No reason provided by the coder.";
                if (risk.Length == 0) risk = "Unspecified risk. Human review required.";

                proposals.Add(new PatchProposal
                {
                    FilePath = filePath, ChangeType = EnumExtensions.ParsePatchChangeType(changeType), Reason = reason,
                    Risk = risk, OldContent = oldContent, NewContent = newContent, RequiresApproval = true, Status = PatchStatus.Proposed,
                });
            }
            catch { /* skip the malformed proposal, keep the rest */ }
        }
        return new PatchSet { MissionId = missionId, TaskId = taskId, Summary = summary, Proposals = proposals };
    }

    // Returns string value or null for both missing keys and explicit JSON null values.
    private static string? JsonStrOrNull(System.Text.Json.Nodes.JsonNode? node)
    {
        if (node is null) return null;
        if (node is System.Text.Json.Nodes.JsonValue v &&
            v.GetValueKind() == System.Text.Json.JsonValueKind.Null) return null;
        try { return node.GetValue<string>(); } catch { return null; }
    }
}
